# Dev environment stack group config
# --------------------------------------
sceptre_user_data:
  subdomain: 'dmproadmap'
  domain: !ssm_parameter /uc3/dmp/dev/hosted_zone_name
  application: 'uc3-dmp-roadmap'
  env: 'dev'
  rails_env: 'ci'
  rails_log_level: 'debug'

stack_tags:
  Program: 'uc3'
  Service: 'dmp'
  Subservice: 'roadmap'
  Environment: 'dev'
  CodeRepo: 'https://github.com/CDLUC3/dmp-roadmap-cfn.git'
  Contact: 'briley'
