template:
  path: 'frontend.yaml'
  type: 'file'

parameters:
  VpcID: !stack_output_external cdl-uc3-dev-vpc-stack::vpc
  Subnets:
    - !stack_output_external cdl-uc3-dev-defaultsubnet-stack::defaultsubnet2a
    - !stack_output_external cdl-uc3-dev-defaultsubnet-stack::defaultsubnet2b
    - !stack_output_external cdl-uc3-dev-defaultsubnet-stack::defaultsubnet2c

  HostedZoneID: !stack_output_external sceptre-uc3-ops-common-dev-route53::HostedZoneID

  Environment: !stack_attr sceptre_user_data.env
  AppName: !stack_attr sceptre_user_data.application
  Subdomain: !stack_attr sceptre_user_data.subdomain
  Domain: !stack_attr sceptre_user_data.domain
